tmp

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,48 +11,55 @@ jobs:
 
       - name: "Cache: prepare /nix/store"
         run: |
+          # Create with liberal rights, otherwise cache action will complain
+          # about permission errors.
           sudo mkdir -p /nix/store
-          sudo chown -R $(whoami):$(whoami) /nix/store
+          sudo chmod -R 777 /nix
 
-      - name: "Cache /nix/store"
+      # See https://github.com/cachix/install-nix-action/issues/56#issuecomment-1030697681
+      - name: Cache nix env take N+1
         uses: actions/cache@v2
         env:
-          cache-name: tmp7
+          cache-name: tmp8
         with:
           path: |
-            /nix/store
-          key: ${{ env.cache-name }}-${{ hashFiles('./flake.lock') }}-${{ hashFiles('./flake.nix') }}-${{ hashFiles('**/*.cabal') }}
-          restore-keys: |
-            ${{ env.cache-name }}-${{ hashFiles('./flake.lock') }}-${{ hashFiles('./flake.nix') }}-${{ hashFiles('**/*.cabal') }}
-            ${{ env.cache-name }}-${{ hashFiles('./flake.lock') }}-${{ hashFiles('./flake.nix') }}-
-            ${{ env.cache-name }}-${{ hashFiles('./flake.lock') }}-
-            ${{ env.cache-name }}-
+            /nix/store/**
+            # Missing something?
+            /nix/var/nix/*/*
+            /nix/var/nix/db/*
+            /nix/var/nix/db/*/**
+            !/nix/var/nix/daemon-socket/socket
+            !/nix/var/nix/userpool/*
+            !/nix/var/nix/gc.lock
+            !/nix/var/nix/db/big-lock
+            !/nix/var/nix/db/reserved
+          key: ${{ runner.os }}-nix-store
 
       - name: "Install nix"
         uses: cachix/install-nix-action@v16
         with:
           nix_path: nixpkgs=channel:nixos-unstable
 
-      - name: "Cache: let /nix/store owned by root"
-        run: |
-          sudo chown -R root:root /nix/store
-          ls -ld /nix/store/ahzi8gfj34762a0yccafanspwylqj1z4-glibc-locales-2.33-108 || true
-          lsblk
+      # - name: "Cache: let /nix/store owned by root"
+      #   run: |
+      #     sudo chown -R root:root /nix/store
+      #     ls -ld /nix/store/ahzi8gfj34762a0yccafanspwylqj1z4-glibc-locales-2.33-108 || true
+      #     lsblk
 
       - name: "Build and test"
         run: |
           nix build
 
-      - name: Check /nix/store/ahzi8gfj34762a0yccafanspwylqj1z4-glibc-locales-2.33-108
-        run: |
-          ls -ld /nix/store/ahzi8gfj34762a0yccafanspwylqj1z4-glibc-locales-2.33-108 || true
-          lsblk
+      # - name: Check /nix/store/ahzi8gfj34762a0yccafanspwylqj1z4-glibc-locales-2.33-108
+      #   run: |
+      #     ls -ld /nix/store/ahzi8gfj34762a0yccafanspwylqj1z4-glibc-locales-2.33-108 || true
+      #     lsblk
 
       - name: "Build and test (flake)"
         run: |
           nix flake check
 
-      # Since actions/cache@v2 runs as runner, /nix/store should be owned by runner
-      - name: "Cache: let /nix/store owned by runner"
-        run: |
-          sudo chown -R $(whoami):$(whoami) /nix/store
+      # # Since actions/cache@v2 runs as runner, /nix/store should be owned by runner
+      # - name: "Cache: let /nix/store owned by runner"
+      #   run: |
+      #     sudo chown -R $(whoami):$(whoami) /nix/store
